export const Profile = {
  objective:
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled ",
  personal_info: {
    name: "Jane Doe",
    email: "janedoe@gmail.com",
    contact_no: "+91889945612",
    linkedIn: "pranav194",
    hobbies: ["travelling", "fifa"],
    highest_education: "highest Education",
  },
  education: [
    {
      title: "High School",
      school_name: "High School",
      board: "ICSE",
      score: "95",
      year: "2015",
      id: 1,
    },
    {
      title: "Intermediate School",
      school_name: "Intermediate School",
      board: "ISC",
      score: "95",
      year: "2017",
      id: 2,
    },
    {
      title: "Graduation",
      school_name: "High School",
      board: "ICSE",
      score: "95",
      year: "2015",
      id: 3,
    },
  ],
  skill: [
    { skill_name: "React", skill_profiency: "1", id: 1 },
    { skill_name: "Vue", skill_profiency: "10", id: 2 },
    { skill_name: "Material Ui", skill_profiency: "3", id: 3 },
  ],
  work_experience: [
    {
      title: "lorem epsum",
      position: "Software engineer",
      location: "Gurugram",
      organisation_name: "Edunomics",
      duration: "1 year 2 months",
      start: "2019",
      end: "present",
      text: "lorem epsum",
      id: 1,
    },
    {
      id: 2,
      title: "lorem epsum",
      position: "Software engineer",
      location: "Gurugram",
      organisation_name: "Edunomics",
      duration: "1 year 2 months",
      start: "2019",
      end: "present",
      text: "lorem epsum",
    },
  ],
  project: [
    {
      id: 1,
      project_name: "lorem epsum",
      subtitle: "lorem",
      location: "IIT BHU",
      duration: "2 months",
      start: "2017",
      description: "something about the project",
    },
  ],
  achievement: [
    "achieved first rank in a college event",
    "was first in a hackethon",
  ],
};
